version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: UTC
    target-branch: main
    open-pull-requests-limit: 2
    rebase-strategy: auto
    groups:
      gomod-minor-patch:
        applies-to: version-updates
        update-types: ["minor", "patch"]
        patterns: ["*"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/jackc/pgx/v5"
        versions: ["5.7.5", "5.7.6", ">= 5.8.0"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: UTC
    target-branch: main
    open-pull-requests-limit: 2
    rebase-strategy: auto
    groups:
      actions-minor-patch:
        applies-to: version-updates
        update-types: ["minor", "patch"]
        patterns: ["*"]
