name: 📝 Other Issue
description: Create an issue that doesn't fit the other templates
title: ""
labels: ["needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Use this template for issues that don't fit our other categories. Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting this issue
      options:
        - label: I have searched existing issues to ensure this hasn't been reported already
          required: true
        - label: I have read the [CONTRIBUTING.md](../CONTRIBUTING.md) guidelines
          required: true
        - label: This issue doesn't fit any of the other issue templates
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your issue, question, or request
      placeholder: Provide a clear and detailed description...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category best describes this issue?
      options:
        - Question
        - Discussion
        - Proposal
        - Research
        - Infrastructure
        - Process/Workflow
        - Community
        - Legal/Licensing
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, links, or information
      placeholder: Any additional information that would be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
