name: 🔒 Security Vulnerability
description: Report a security vulnerability (Use this template for responsible disclosure)
title: "[SECURITY] "
labels: ["security", "critical", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT SECURITY NOTICE** ⚠️
        
        If you believe you have found a security vulnerability that could potentially harm users or the network, please consider using our **private security disclosure process** instead of this public issue tracker.
        
        **For critical security vulnerabilities, please email the maintainers directly or check our [SECURITY.md](../SECURITY.md) for responsible disclosure guidelines.**
        
        Only use this public template for:
        - Non-critical security improvements
        - Security-related feature requests
        - Security documentation issues
        - Issues that are already publicly known

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting this security report
      options:
        - label: I have read the [SECURITY.md](../SECURITY.md) file
          required: true
        - label: I understand this is a public issue and not suitable for critical vulnerabilities
          required: true
        - label: I have considered whether this should be reported privately first
          required: true

  - type: dropdown
    id: severity-level
    attributes:
      label: Severity Level
      description: How would you classify the severity of this security issue?
      options:
        - Low - Security improvement suggestion
        - Medium - Potential security concern
        - High - Confirmed vulnerability with limited impact
        - Critical - Should be reported privately
    validations:
      required: true

  - type: textarea
    id: vulnerability-summary
    attributes:
      label: Security Issue Summary
      description: A brief summary of the security issue (avoid detailed exploitation steps in public)
      placeholder: |
        Provide a high-level summary of the security concern without revealing sensitive details.
        For critical vulnerabilities, please use private disclosure channels.
    validations:
      required: true

  - type: dropdown
    id: vulnerability-category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Input Validation
        - Data Exposure
        - Denial of Service
        - Configuration Security
        - Cryptographic Issue
        - Network Security
        - Access Control
        - Rate Limiting
        - Code Injection
        - Information Disclosure
        - Other
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the relay are affected?
      placeholder: |
        - Affected modules/packages
        - Affected endpoints or functionality
        - Affected configurations
    validations:
      required: true

  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this security issue?
      placeholder: |
        Describe the potential impact:
        - What could an attacker achieve?
        - What data/functionality is at risk?
        - How many users/relays could be affected?
        - Are there any mitigating factors?
    validations:
      required: true

  - type: dropdown
    id: disclosure-timeline
    attributes:
      label: Disclosure Status
      description: What is the current disclosure status?
      options:
        - First discovery - not publicly known
        - Publicly known issue
        - CVE assigned
        - Fix available elsewhere
        - Academic research disclosure
    validations:
      required: true

  - type: textarea
    id: version-info
    attributes:
      label: Version Information
      description: Which versions are affected?
      placeholder: |
        - Affected versions: 
        - First affected version: 
        - Latest tested version: 
        - Fixed in version (if known):
    validations:
      required: true

  - type: textarea
    id: reproduction-info
    attributes:
      label: Reproduction Information
      description: General information about reproducing the issue (avoid detailed exploitation steps)
      placeholder: |
        ⚠️ Provide only general reproduction information. Do not include:
        - Detailed exploitation steps
        - Working proof-of-concept code
        - Specific attack vectors
        
        Instead, provide:
        - General conditions where this occurs
        - Configuration requirements
        - High-level steps to identify the issue

  - type: textarea
    id: mitigation-suggestions
    attributes:
      label: Suggested Mitigations
      description: Do you have suggestions for mitigating or fixing this issue?
      placeholder: |
        - Immediate mitigation steps
        - Configuration changes
        - Suggested fixes
        - Security improvements

  - type: checkboxes
    id: nostr-specific
    attributes:
      label: Nostr-Specific Context
      description: Check if any of these Nostr-specific areas are involved
      options:
        - label: Event validation and filtering
        - label: NIP implementation security
        - label: Client authentication
        - label: Event signing/verification
        - label: Relay-to-relay communication
        - label: WebSocket connection handling
        - label: Rate limiting and abuse prevention

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant references, documentation, or similar issues
      placeholder: |
        - CVE references
        - Security advisories
        - Research papers
        - Similar issues in other projects
        - Relevant security guidelines

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: Responsible Disclosure
      description: Responsible disclosure commitment
      options:
        - label: I commit to not publicly exploit this vulnerability
        - label: I will give maintainers reasonable time to address the issue
        - label: I understand this may be made private if deemed critical
        - label: I agree to follow responsible disclosure practices

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to follow our Code of Conduct and Security Policy
      options:
        - label: I agree to follow this project's Code of Conduct and Security Policy
          required: true
