# Development Configuration for Shugur Relay
# Developer-friendly settings with detailed logging and debugging

GENERAL:
  # Reserved for future general configuration options

LOGGING:
  LEVEL: debug                    # Log level (debug, info, warn, error)
  FILE:                          # Path for the log file (optional)
  FORMAT: console                # Log format (console, json)
  MAX_SIZE: 20                   # Maximum size of the log file in MB
  MAX_BACKUPS: 10                # Maximum number of backup files
  MAX_AGE: 14                    # Maximum age of backup files in days

METRICS:
  ENABLED: true                  # Enable metrics collection
  PORT: 8182                     # Port for Prometheus metrics

RELAY:
  NAME: "shugur-relay-dev"       # Relay name (max 30 chars, shown in NIP-11)
  DESCRIPTION: "High-performance, reliable, scalable Nostr relay for decentralized communication - Development" # Relay description (max 200 chars, shown in NIP-11)
  CONTACT: "dev@shugur.com"      # Relay contact email (shown in NIP-11)
  ICON: "https://github.com/Shugur-Network/relay/raw/main/logo.png" # Relay icon URL (shown in NIP-11)
  BANNER: "https://github.com/Shugur-Network/relay/raw/main/banner.png" # Relay banner URL (optional, shown in NIP-11)
  WS_ADDR: ":8081"              # WebSocket listening address
  PUBLIC_URL: "ws://localhost:8081" # Public URL (optional)
  EVENT_CACHE_SIZE: 10000        # Event cache size
  SEND_BUFFER_SIZE: 4096         # WebSocket send buffer size
  WRITE_TIMEOUT: 10s             # WebSocket write timeout
  IDLE_TIMEOUT: 60s              # Connection idle timeout
  THROTTLING:
    MAX_CONTENT_LENGTH: 65536    # Maximum content length in bytes
    MAX_CONNECTIONS: 100         # Maximum concurrent connections
    BAN_THRESHOLD: 10            # Number of violations before ban
    BAN_DURATION: 60             # Ban duration in seconds
    RATE_LIMIT:
      ENABLED: true              # Enable rate limiting
      MAX_EVENTS_PER_SECOND: 1000 # Maximum events per second
      MAX_REQUESTS_PER_SECOND: 1000 # Maximum requests per second
      BURST_SIZE: 100            # Rate limit burst size
      PROGRESSIVE_BAN: false     # Enable progressive ban duration
      MAX_BAN_DURATION: 5m       # Maximum ban duration

RELAY_POLICY:
  BLACKLIST:
    PUBKEYS: []                  # List of pubkeys to blacklist (hex format)
  WHITELIST:
    PUBKEYS: []                  # List of pubkeys to whitelist (hex format)

CAPSULES:
  ENABLED: true                  # Enable Time Capsules feature
  MAX_WITNESSES: 10              # Maximum number of witnesses allowed per time capsule

DATABASE:
  SERVER: "localhost"            # Database server hostname
  PORT: 26260                    # Database port (matches dev docker-compose)
