name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    name: Enable auto-merge for Dependabot (minor/patch)
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - name: Set up Go (for caching)
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          cache: true
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375b2a1a4905ee5 # v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge (squash) for minor/patch updates
        if: ${{ steps.meta.outputs.update-type == 'version-update:semver-minor' || steps.meta.outputs.update-type == 'version-update:semver-patch' }}
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627492c4047346bed75f8b9cf837 # v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
