name: Trivy Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  trivy-fs:
    name: Trivy FS Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy filesystem scan (CRITICAL,HIGH)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          severity: CRITICAL,HIGH
          exit-code: '1'
          vuln-type: 'os,library'
          hide-progress: true

