name: "Validate PR Title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Validate PR title
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const title = context.payload.pull_request.title;
            const validTypes = ['fix', 'feat', 'docs', 'style', 'refactor', 'perf', 'test', 'build', 'ci', 'chore', 'revert', 'deps', 'docker', 'security', 'config'];
            
            // Check if title follows conventional commit format
            const conventionalCommitRegex = /^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert|deps|docker|security|config)(\(.+\))?: .+/;
            
            if (!conventionalCommitRegex.test(title)) {
              core.setFailed(`PR title "${title}" does not follow conventional commit format. Expected format: "type(scope): description" where type is one of: ${validTypes.join(', ')}`);
              return;
            }
            
            // Check that subject doesn't start with uppercase
            const match = title.match(/^[a-z]+(\(.+\))?: (.+)/);
            if (match && match[2] && /^[A-Z]/.test(match[2])) {
              core.setFailed(`PR title subject "${match[2]}" should not start with an uppercase character. Please use lowercase for the first word.`);
              return;
            }
            
            console.log(`✅ PR title "${title}" is valid`);